#spring:
#  jms:
#    template:
#      default-destination: tacocloud.order.queue
#  artemis:
#    host: localhost
#    port: 61616
#    user: tacoweb
#    password: WqNu4BcY
#    embedded:
#      enabled: false



#spring:
#  kafka:
#    template:
#      default-topic: tacocloud.orders.topic
#    bootstrap-servers:
#      - localhost:9092
#    producer:
#      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
