spring:
  rabbitmq:
    host: localhost
    port: 5672
#spring:
#  jms:
#    template:
#      receive-timeout: 2
#  artemis:
#    host: localhost
#    port: 61616
#    user: tacoweb
#    password: WqNu4BcY
#    embedded:
#      enabled: false


#spring:
#  kafka:
#    bootstrap-servers:
#      - localhost:9092
#    consumer:
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      group-id: tacocloud_kitchen
#      auto-offset-reset: earliest
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.example.producer.model
